# Generated by Django 4.0.6 on 2022-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('finished', 'Finished')], default=('low', 'Low'), max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], default=('medium', 'Medium'), max_length=20)),
                ('importance', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
