# Generated by Django 4.0.6 on 2022-08-01 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('t', 'todo'), ('ip', 'in_progress'), ('b', 'blocked'), ('f', 'finished')], default=('l', 'low'), max_length=20)),
                ('priority', models.CharField(choices=[('l', 'low'), ('h', 'high'), ('m', 'medium')], default=('m', 'medium'), max_length=20)),
                ('importance', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
