# Generated by Django 4.0.6 on 2022-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_is_confirmed_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank='true', max_length=50, null='true'),
            preserve_default='true',
        ),
    ]
